# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 00:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_auto_20161025_0245'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=120, verbose_name='Street and number')),
                ('poiny', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('custom_city', models.CharField(blank=True, max_length=40)),
                ('custom_postal_code', models.CharField(blank=True, max_length=15, verbose_name='Postal code')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.City', verbose_name='City')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.District', verbose_name='District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities.Region', verbose_name='Region')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Subregion', verbose_name='Subregion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericContactField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VCS', [('GITHUB', 'Github'), ('BITBUCKET', 'Bitbucket'), ('GITLAB', 'Gitlab')]), ('Social', [('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('GOOGLE-PLUS', 'Google+'), ('LINKEDIN', 'LinkedIn'), ('PINTEREST', 'Pinterest'), ('TUMBLR', 'Tumblr'), ('WEBSITE', 'Website')]), ('Communication', [('TELEPHONE', 'Telephone'), ('MOBILE', 'Mobile'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('SKYPE', 'Skype'), ('FMESSENGER', 'Facebook Messenger'), ('LINE', 'Line'), ('IRC', 'IRC'), ('JABBER', 'Jabber/XMPP')])], max_length=25, verbose_name='Type')),
                ('value', models.CharField(max_length=150, verbose_name='Value')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
