# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Logo')),
                ('target', models.CharField(choices=[('LOCAL', 'Local'), ('REGION', 'Region'), ('COUNTRY', 'Country'), ('INTERNATIONAL', 'International')], default='LOCAL', max_length=18)),
                ('foundation_date', models.DateField(auto_now_add=True)),
                ('death_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('position', models.CharField(blank=True, max_length=30)),
                ('executive_board', models.BooleanField(default=False)),
                ('since', models.DateTimeField(blank=True, help_text='If a user has never been as active, this will be null.', null=True, verbose_name='Since')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_association.Association')),
            ],
        ),
    ]
