# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_contact', '0001_initial'),
        ('cms_association', '0001_initial'),
        ('cms_people', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_people.Person'),
        ),
        migrations.AddField(
            model_name='association',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_contact.Address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='association',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(through='cms_association.Membership', to='cms_people.Person'),
        ),
        migrations.AddField(
            model_name='association',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_association.Association', verbose_name='Parent association'),
        ),
    ]
