# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms_contact', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, max_length=12000, verbose_name='Biography')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('real_name_privacy', models.CharField(choices=[('HIDDEN', 'Hidden'), ('ONLYMEMBERS', 'Only Members'), ('VISIBLE', 'Always visible')], default='VISIBLE', max_length=20, verbose_name='Real name privacy')),
                ('address_privacy', models.CharField(choices=[('HIDDEN', 'Hidden'), ('ONLYREGION', 'Show only region'), ('ONLYCITY', 'Show only city'), ('COMPLETE', 'Show full address')], default='ONLYCITY', max_length=20, verbose_name='Address privacy')),
                ('bio_privacy', models.CharField(choices=[('HIDDEN', 'Hidden'), ('ONLYMEMBERS', 'Only Members'), ('VISIBLE', 'Always visible')], default='VISIBLE', max_length=20, verbose_name='Bio privacy')),
                ('email_privacy', models.CharField(choices=[('HIDDEN', 'Hidden'), ('ONLYMEMBERS', 'Only Members'), ('VISIBLE', 'Always visible')], default='ONLYMEMBERS', max_length=20, verbose_name='Email privacy')),
                ('telephones_privacy', models.CharField(choices=[('HIDDEN', 'Hidden'), ('ONLYMEMBERS', 'Only Members'), ('VISIBLE', 'Always visible')], default='ONLYMEMBERS', max_length=20, verbose_name='Telephones privacy')),
                ('news', models.BooleanField(default=True, verbose_name='News')),
                ('nearby_new_members', models.BooleanField(default=True, verbose_name='Nearby new members')),
                ('nearby_new_associations', models.BooleanField(default=True, verbose_name='Nearby new associations')),
                ('nearby_new_jobs', models.BooleanField(default=False, verbose_name='Nearby new jobs')),
                ('nearby_new_events', models.BooleanField(default=True, verbose_name='Nearby new events')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_contact.Address', verbose_name='Address')),
                ('interests', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
