# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-27 01:39
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('cms_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='interests',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Interests'),
        ),
    ]
