# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 02:00
from __future__ import unicode_literals

import cms_people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_people', '0002_auto_20161027_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=cms_people.models.avatar_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephones_privacy',
            field=models.CharField(choices=[('HIDDEN', 'Hidden'), ('ONLYMEMBERS', 'Only Members'), ('VISIBLE', 'Always visible')], default='HIDDEN', max_length=20, verbose_name='Telephones privacy'),
        ),
    ]
