# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms_event', '0001_initial'),
        ('cms_contact', '0001_initial'),
        ('cms_people', '0001_initial'),
        ('cms_association', '0002_auto_20161025_0245'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='speakers',
            field=models.ManyToManyField(to='cms_people.Person', verbose_name='Speakers'),
        ),
        migrations.AddField(
            model_name='priceevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_event.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_contact.Address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='event',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms_association.Association'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendances',
            field=models.ManyToManyField(through='cms_event.Attendance', to='cms_people.Person', verbose_name='Attendances'),
        ),
        migrations.AddField(
            model_name='event',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Interests'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_event.Event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_people.Person'),
        ),
    ]
